### ISSUE TITLE
Data isn't related to data on Eforsyning webpage

### ISSUE THREAD

**Issue by smathev** [kpoppel/homeassistant-eforsyning#19]
Hi. 

Installed the component via HACS yesterday, and set up an integration. Have a mini-graph running showing water-temperature return vs expected water temperature return. But, the data in Home Assistant isn't remotely related to the data I'm seeing on the homepage. 

So, for both yesterday and today it's showing a return temperature of 36.11, but on eForsyningen it's showing a temperature of 32 for yesterday and 30.95 for today.

I haven't messed with the recorder in any way, it's simply left to the original settings from HA on install, but I should think it would hold 48 hours of data?

This is my mini-graph:
![image](https://user-images.githubusercontent.com/2720266/173532665-17adb4de-12c7-451c-9294-1cddadfec5ca.png)

Using code:
```
type: custom:mini-graph-card
hours_to_show: 48
smoothing: false
group_by: date
name: Fjernvarme - vand temperatur
entities:
  - entity: sensor.eforsyning_water_temperature_return
    name: Tilbageløb
  - entity: sensor.eforsyning_water_temperature_exp_return
    name: Forventet tilbageløb
```

I've setup the logger to debug, as suggested in your configuration but I'm not seeing any issues. 

I found my ForsyningsID using a different method, as your method wasn't working - it seems when I search for 'getv' in the Network-Tab I don't get any results.  I found it, looking at the webpage source-code when I was at the login screen for my supplier: 

`forsyningId: "10340F7C-C2B6-4009-BFFD-135C92EDC28A"`

I hope you can help me resolve this issue :)

**Comment by kpoppel** [comment]
This is my configuration which works for me:

```
type: custom:mini-graph-card
hours_to_show: 720
smoothing: false
group_by: date
name: Fjernvarme - afkøling
entities:
  - entity: sensor.eforsyning_water_temperature_forward
    name: Fremløb
  - entity: sensor.eforsyning_water_temperature_cooling
    name: Afkøling
  - entity: sensor.eforsyning_water_temperature_return
    name: Retur
  - entity: sensor.eforsyning_water_temperature_exp_return
    name: Forventet Retur
```

Your look the same, so I would definitely expect this to work for you.

Using the web interface of eforsyning this data looks this:

![image](https://user-images.githubusercontent.com/4174578/177118085-0a1cf4f4-a606-4f6c-8c04-56514d9bc0a7.png)

My data in HomeAssistant are consistent with this.  What I do observe is that during Summer the temperatures really does not move that much if your house is BR2020 for instance.  Give it some time.  If you get numbers like you show, everything should be fine.
