### ISSUE TITLE
Historiske data gentages 14 gange

### ISSUE THREAD

**Issue by jnxxx** [kpoppel/homeassistant-eforsyning#30]
Jeg ser du har fundet en måde at vise historiske data i en graf, selv om HA ellers ikke supporterer at indsætte andet end aktuelle data i databasen.
Det er for så vidt fint, omend det strider lidt mod tankegangen i designed med HA.
Men er det ikke unødvendig at gentage samme datasæt 14 gange?

På nuværende tidspunkt fylder data sektionen for én sensor 5390 linier, og det indsættes på alle sensorer. Dvs. pt. 75460 linier, og sidst på året vil det fylde 112420 linier.

Det bevirker at når man går ind i Developer Tools / States er den blevet langsommere til at indlæse siden. Og noget uoverskuelig og træls at bladre i.

Kunne man ikke nøjes med at indsætte disse data én gang?

Det kunne være som nu, men blot på en enkelt sensor.
Eller indsat som nu på hver sensor, men data array'et begrænset til samme måling som sensoren.

F.eks. for: sensor.eforsyning_energy_start
```
data: 
- DateFrom: '2021-12-31T00:00:00.000Z'
  DateTo: '2022-01-01T00:00:00.000Z'
  kWh-Start: 11949
- DateFrom: '2022-01-01T00:00:00.000Z'
  DateTo: '2022-01-02T00:00:00.000Z'
  kWh-Start: 12003
```

Det giver stadig noget overhead med DateFrom og DateTo, men må alt andet lige spare ganske mange linier.

Begge forslag burde kunne fungere med apexcharts.
Sidste forslag helt som nu, blot at man skal sørge for at der er en sammenhæng imellem angivet entity og attribut i data_generator (som dine eksempler viser).

Ved andet forslag kan man tilrette således:
```
  - entity: sensor.eforsyning_energy_used
    name: Forward
    unit: °C
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["Temp-Forward"]];
      });

```
Altid angive samme entity, og i data_generator så angive den ønskede attribut.
Eneste ulempe er, at man herforuden skal sætte name og unit selv.
