### ISSUE TITLE
[BUG] Last reset is missing

### ISSUE THREAD

**Issue by jeppemedleen** [kpoppel/homeassistant-eforsyning#67]
Please help me help you:

- [ ] Describe what you experience and what the expectation was
When using the entity Eforsyning_water_used it states that the last reset is missing
- [ ] If relevant, please post screenshots
![image](https://github.com/kpoppel/homeassistant-eforsyning/assets/77433939/eae99e81-d020-43c1-a70a-4332eaed9fba)
![image](https://github.com/kpoppel/homeassistant-eforsyning/assets/77433939/6257ea69-608d-4198-b8db-69ca26bff2af)

**Comment by mm98** [comment]
@jeppemedleen If you know how to add a template sensor by YAML. You could add the following, to get water consumption working in the Energy area. This will always be one day delayed, even though it will be shown today.

```yaml
- platform: template
  sensors:
    eforsyning_water_usage_total:
      friendly_name: "EForsyning: Water usage (total)"
      unique_id: eforsyning_water_usage_total
      unit_of_measurement: m³
      device_class: water
      availability_template: >
        {{ has_value("sensor.eforsyning_water_end") and states("sensor.eforsyning_water_end") | float(0) > 0 }}
      value_template: >-
        {{ states("sensor.eforsyning_water_end") | float(0) }}
      attribute_templates:
        state_class: total_increasing
        last_reset: >
          {{ ((state_attr("sensor.eforsyning_water_end", "data") | sort(attribute="date", reverse=true))[0].date | as_datetime).isoformat() }}
```
