### ISSUE TITLE
Add state properties state_class and last_reset

### ISSUE THREAD

**Issue by kpoppel** [kpoppel/homeassistant-eforsyning#9]
This blog post
  https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/
outlines two new sensor properties to enable long term statistics.  I am not sure how to apply this to these sensors, but may look into this one day.

This blog post already removed the last_reset property:
  https://developers.home-assistant.io/blog/2021/08/16/state_class_total

**Comment by cokeman0** [comment]
Hej,

Indtil næste version af eforsyning, er løsningen at rette customize.yaml med følgende

virker med 2021.8 og 2021.9 og bemærk at MWh er rettet til kWh...

```
sensor.eforsyning_energy_exp_used:
  unit_of_measurement: kWh
  device_class: energy
  state_class: measurement
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.eforsyning_energy_used:
  unit_of_measurement: kWh
  device_class: energy
  state_class: measurement
  last_reset: '1970-01-01T00:00:00+00:00'
sensor.eforsyning_water_temperature_exp_return:
  state_class: measurement
  device_class: temperature
sensor.eforsyning_water_temperature_forward:
  state_class: measurement
  device_class: temperature
sensor.eforsyning_water_temperature_return:
  state_class: measurement
sensor.eforsyning_water_temperature_meas_return:
  state_class: measurement
  device_class: temperature
```
